apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
- ../../base
- namespace.yml

patchesStrategicMerge:
- config.yml

images:
- name: api
  newName: mosheshi/basic-go-api
  newTag: f35882d6f0b41ef65b1dc3a7f19df02b1f6da701

patches:
- patch: |-
    - op: add
      path: /spec/rules/0/host
      value: k8satl.k8s-meetup.s5t.dev
    - op: add
      path: /spec/tls/0/hosts/0
      value: k8satl.k8s-meetup.s5t.dev
  target:
    kind: Ingress
    name: k8s-meetup-api
- patch: |-
    - op: add
      path: /spec/template/metadata/namespace
      value: prod
  target:
    kind: SealedSecret
    name: k8s-meetup-api-secret
