apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yml
  - deployment.yml
  - ingress.yml
  - sealedsecret.yml
  - service.yml

commonLabels:
  app.kubernetes.io/component: api
  app.kubernetes.io/name: k8s-meetup