apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: k8s-meetup-api-secret
spec:
  encryptedData:
    password: AgAQ+aXVWBb3Q9Q2NXJOFGNKspJXp1A+8UnS2/FOtKQR28FFZ/RF0Ef/DJRu9nKiW0T7YAZ4BWIix+Y6iMra9SATG6tVQQX1jbXALiJ++LhGP8EDLrN9zNSWp12EHBf+LPRmr/Ng2FF8r81640I5fh/sefyxeiLXRgumJ6Ghq8nM5SavMMWKeZ6qO0F1QgCGeljcOITaUgeY4zdMyY3wnm6xkuJoVFsmfQfPBSklTejsMPk5l5SebplYJSo4+/H9tN/N0ryfruh9Vsr+pRxsSlwguW7osbP1aBezo9PgWc9rNLcWXp9eLWvOIZl+3cVnzejS6lNV9ixW4hLHpZPHLGqNNHKYcAftLCbUkRc3sABTLf4/Iu3/ncSXV1ixTIs7fIi/GaXY+4+DbVcnE42dCHB7yKfmwKyfZu0kZ2ATQzK+SdkpOJIf1gfWWz08nkceLikRqo538FF1U74T+uetPkxYSrDPA1js+sf8e4rt3UhYTEF8FS38mmw9lj6+7F0wK5OjRWdw4xPvHv+KVAJQT6bqxE7LwTn+3pzwJOIJoanZin9drwIZ+YEFT0c2SxYuskncf/pDLOeep1oDPPk8bS7lqn7U7A/bDkgmBaSSGMD3FpnHRDzaww2Rqy4QqFP49TXXfPXzySHYpZoYoBe5aVn+MEgESMGHdv3M7Khn8rBBJ10sQ8dvkIAvhHWHpkvaFbFW9Je/gQJE+/XITHxS3pXy
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: k8s-meetup-api-secret

