name: CI/CD

on:
  push:
    branches: [ qa, main ]
    paths-ignore:
      - 'k8s/**'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "4.2.0"

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push - QA Image
      if: ${{ github.ref == 'refs/heads/qa' }}
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          mosheshi/basic-go-api-qa:${{ github.sha }}
  
  update-manifests:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update k8s Config - QA
      if: ${{ github.ref == 'refs/heads/qa' }}
      run: |
        git checkout qa
        cd k8s/overlays/qa
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        kustomize edit set image api=mosheshi/basic-go-api-qa:$GITHUB_SHA
        cat kustomization.yml
        git commit -am "Bump image tag"
        git push origin qa
    - name: Update k8s Config - PROD
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        git checkout main
        cd k8s/overlays/prod
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        kustomize edit set image api=mosheshi/basic-go-api:$GITHUB_SHA
        cat kustomization.yml
        git commit -am "Bump image tag"
        git push origin main
